name: Update README stats
on:
  schedule: [{cron: "0 3 * * *"}] # Runs daily
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: readme-tools/github-readme-stats-action@v1
        with:
          path: profile/stats.svg
          token: ${{ secrets.PAT_TOKEN }}
      - name: Commit changes
        run: |
          git config user.name github-actions
          git push
